### ISSUE TITLE
Insert link client side instead of parsing @syntax server-side

### ISSUE THREAD

**Issue by ewinslow** [Elgg/mentions#21]
Pros:
- Author can modify link text
- Can mention any other entity on the site, not just users
- Less server-side parsing required
  - performance benefit
  - Issues #17 and #12 go away automatically
- `<a>` tags are part of a standard. `@mentions` are not.
- We already need to solve the broken-link problem, so this just makes it easier for people to link to things.
- There's a handy library for it ( https://github.com/ichord/At.js )

Cons:
- Links break. Server-side parsing means they could be kept up-to-date or auto-removed.
- ECML could give us the best of both worlds

NB: I say "instead of" but that just means going forward. We'd still need to support server-side `@mention` for BC, I'm sure.
## Votes

In favor of storing the full link to the mentioned entity (`<a href>...</a>`):
- Evan
- Steve

In favor of just storing `@mention`:
- Juho
- Matt

**Comment by Wouter0100** [comment]
To get back in this discussion, I'm personally for saving the `@mention` to a DB, instead of a `<a>`. A mention is a mention, nothing more. The user shouldn't be able to mess around with it. Google+, Facebook and Github doesn't replace it with a `<a>` either (from the users perspective), just because it isn't user friendly, if you ask me.

It also takes a lot of problems if you have hard coded links in the DB, for example when you switch between domains or you get an SSL certificate.

What we could do is just store `@mention`, print that to the browser and let a JS script takes care of the `@mention` -to-`<a>` conversion on the clients side (over the whole site), instead of a server-side script.

Or, we could get the `ob_start` and [preg_match](http://stackoverflow.com/questions/23221732/regular-expression-to-detect-mentions-but-not-detecting-emails) it (I'm unsure if there is a hook for that?)
