### ISSUE TITLE
i am seeing 3 notifications when i am mentioned in a wire post

### ISSUE THREAD

**Issue by propertunist** [Elgg/mentions#34]
i just saw that i am receiving 3 separate email and notifier notifications when i am mentioned in a wire post. 
1 comes from thewire_tools and uses the string: "You've been mentioned on the wire"
1 is the default notification for a friend posting a wire post
1 appears to be from either mentions or notifier and uses the string: "%s mentioned you in %s"

there is only a need for 1 notification for this action and i think it should just be the last one from the mentions plugin.

**Comment by propertunist** [comment]
this is also an issue for other object types. e.g. i get two notifications for comments on videolist items that i have added to the site, one from videolist and one from mentions. it would be better if the two were combined.

**Comment by juho-jaakkola** [comment]
In the latter case, the poster should not be mentioning you in the first place, because it's your post and therefore you're receiving a notification in any case. So technically it's working as intended and it's a mistake of the end user.

But I guess mentions could be altered to check the owner of the container, and send the notification only if notification recipient is not the owner.

**Comment by propertunist** [comment]
if there is a thread under a video, for example, it is common for multiple people to be involved and for one commenter to want to target a specific person with their current comment and not anyone else. this is why you will see the original poster being mentioned in a comment thread under their item. if you look at youtube comments with threaded conversations you will see this in action a lot.
it would be best to send the mention notification in all cases, since it is possible to have multiple mentions for the same item and for them all to be relevant.

**Comment by juho-jaakkola** [comment]
So you would want to prevent the "You have a new comment" notification but not the mentions notification?

This is something that must be implemented in a separate plugin, as otherwise Elgg core would contain feature that is specific to an individual plugin that isn't even bundled within Elgg. Additionally different sites have different needs, so we cannot force a behavior like this through the core.

You can make a plugin that uses e.g. the `'enqueue', 'notification'` hook to check whether the post owner is mentioned in the comment, and prevent the regular notification in that case.

**Comment by propertunist** [comment]
i would suggest just having a notification that combines the comment and the mention into one single one. i thought mentions was intended to be included in core? if so, then this would be an aspect of it that would not be specific to any 3rd party plugin as it would apply equally to comments for blogs, pages or anything else.
